# -*- coding: utf-8 -*-
"""Dixin_Zhang_Assignment 2: Second Research/Programming Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nf6DJ1y0NFnjhppDw5V9ofOFRjkYC76Q

**Name**: `Dixin Zhang`

**Date**: `20/4/2026`

# 1 Import Data
"""

import kagglehub
path = kagglehub.dataset_download("moimransiddiqui/ads-ctr-optimistaion")

import os
import glob
import pandas as pd
import kagglehub

path = kagglehub.dataset_download("moimransiddiqui/ads-ctr-optimistaion")
print("Downloaded to:", path)

for root, dirs, files in os.walk(path):
    for f in files:
        print(os.path.join(root, f))

csv_files = glob.glob(os.path.join(path, "**", "*.csv"), recursive=True)
print("CSV files found:", csv_files)

df = pd.read_csv(csv_files[0])

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nHead:")
display(df.head())

print("\nUnique values per column:")
for col in df.columns:
    print(col, sorted(df[col].dropna().unique())[:10])

import numpy as np
import matplotlib.pyplot as plt

data = df.values
T, k = data.shape

print("Rounds:", T)
print("Number of ads (arms):", k)

"""# 2. ε-greedy

action-value + sample-average + ε-greedy
"""

def run_epsilon_greedy(data, epsilon=0.1):
    T, k = data.shape

    Q = np.zeros(k)   # estimated CTR for each ad
    N = np.zeros(k)   # how many times each ad has been selected

    rewards = []
    chosen_arms = []

    for t in range(T):
        # exploration vs exploitation
        if np.random.rand() < epsilon:
            arm = np.random.randint(k)   # explore
        else:
            max_q = np.max(Q)
            candidates = np.where(Q == max_q)[0]
            arm = np.random.choice(candidates)           # exploit

        reward = data[t, arm]

        N[arm] += 1
        Q[arm] += (reward - Q[arm]) / N[arm]   # sample-average update

        rewards.append(reward)
        chosen_arms.append(arm)

    return np.array(rewards), np.array(chosen_arms), Q, N

np.random.seed(42)

eg_rewards, eg_arms, eg_Q, eg_N = run_epsilon_greedy(data, epsilon=0.1)

print("Total clicks:", eg_rewards.sum())
print("Estimated CTRs:", eg_Q)
print("Selection counts:", eg_N.astype(int))
print("Best estimated ad:", np.argmax(eg_Q) + 1)

avg_reward = np.cumsum(eg_rewards) / np.arange(1, T + 1)
cum_reward = np.cumsum(eg_rewards)

plt.figure(figsize=(8,5))
plt.plot(avg_reward)
plt.xlabel("Round")
plt.ylabel("Average Reward")
plt.title("Epsilon-Greedy: Average Reward Over Time")
plt.show()

plt.figure(figsize=(8,5))
plt.plot(cum_reward)
plt.xlabel("Round")
plt.ylabel("Cumulative Clicks")
plt.title("Epsilon-Greedy: Cumulative Reward")
plt.show()

true_ctr = df.mean(axis=0)
print(true_ctr)
print("Best actual ad:", true_ctr.idxmax(), "CTR =", true_ctr.max())

"""# 3. UCB"""

def run_ucb(data, c=2.0):
    T, k = data.shape

    Q = np.zeros(k)
    N = np.zeros(k)

    rewards = []
    chosen_arms = []

    for t in range(T):
        if t < k:
            arm = t  # try each arm once during warm-up
        else:
            ucb_values = Q + c * np.sqrt(np.log(t + 1) / N)
            max_ucb = np.max(ucb_values)
            candidates = np.where(ucb_values == max_ucb)[0]
            arm = np.random.choice(candidates)  # random tie-breaking

        reward = data[t, arm]

        N[arm] += 1
        Q[arm] += (reward - Q[arm]) / N[arm]

        rewards.append(reward)
        chosen_arms.append(arm)

    return np.array(rewards), np.array(chosen_arms), Q, N

np.random.seed(42)

ucb_rewards, ucb_arms, ucb_Q, ucb_N = run_ucb(data, c=2.0)

print("Total clicks:", ucb_rewards.sum())
print("Estimated CTRs:", ucb_Q)
print("Selection counts:", ucb_N.astype(int))
print("Best estimated ad:", np.argmax(ucb_Q) + 1)

eg_avg = np.cumsum(eg_rewards) / np.arange(1, T + 1)
ucb_avg = np.cumsum(ucb_rewards) / np.arange(1, T + 1)

eg_cum = np.cumsum(eg_rewards)
ucb_cum = np.cumsum(ucb_rewards)

plt.figure(figsize=(8,5))
plt.plot(eg_avg, label="Epsilon-Greedy")
plt.plot(ucb_avg, label="UCB")
plt.xlabel("Round")
plt.ylabel("Average Reward")
plt.title("Average Reward Over Time")
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
plt.plot(eg_cum, label="Epsilon-Greedy")
plt.plot(ucb_cum, label="UCB")
plt.xlabel("Round")
plt.ylabel("Cumulative Clicks")
plt.title("Cumulative Reward Comparison")
plt.legend()
plt.show()

comparison = pd.DataFrame({
    "Ad": [f"Ad {i+1}" for i in range(k)],
    "True CTR": true_ctr.values,
    "EG Estimated CTR": eg_Q,
    "EG Selections": eg_N.astype(int),
    "UCB Estimated CTR": ucb_Q,
    "UCB Selections": ucb_N.astype(int),
})

display(comparison.sort_values("True CTR", ascending=False))

"""# 4.conclution"""

best_arm_index = np.argmax(true_ctr.values)

eg_optimal_rate = np.cumsum(eg_arms == best_arm_index) / np.arange(1, T + 1)
ucb_optimal_rate = np.cumsum(ucb_arms == best_arm_index) / np.arange(1, T + 1)

plt.figure(figsize=(8,5))
plt.plot(eg_optimal_rate, label="Epsilon-Greedy")
plt.plot(ucb_optimal_rate, label="UCB")
plt.xlabel("Round")
plt.ylabel("Optimal Arm Selection Rate")
plt.title("Optimal Ad Selection Rate Over Time")
plt.legend()
plt.show()

print("Final EG optimal-arm rate:", eg_optimal_rate[-1])
print("Final UCB optimal-arm rate:", ucb_optimal_rate[-1])

"""# Results Interpretation

Both ε-greedy and UCB successfully identified Ad 5 as the optimal banner. However, ε-greedy selected the optimal ad much more frequently (68.62%) than UCB (42.92%), which indicates that ε-greedy shifted to exploitation faster on this dataset. UCB explored a wider range of ads for longer, which is consistent with its design of favoring uncertain actions through an upper-confidence bonus. In this dataset, where one ad clearly has the highest CTR, faster exploitation appears to produce better practical performance.
"""